{
 "title": "Vault Token Monitor",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Token Expiration Tim remaining ",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vault_monitor_token_expiration_timestamp_seconds - time()"
    }
   ]
  },
  {
   "title": "Token Expiration Tim remaining ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "vault_monitor_token_expiration_timestamp_seconds - time()",
     "legendFormat": "{{accessor}} - {{display_name}}"
    }
   ]
  },
  {
   "title": "Token Renew Count [10m]",
   "type": "timeseries",
   "description": "nbr of time the token as been renew over a 15min window",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(increase(vault_monitor_token_renew_count[10m])) by (accessor, display_name)",
     "legendFormat": "{{accessor}} - {{display_name}}"
    }
   ]
  },
  {
   "title": "Error Token Lookup Count [10m]",
   "type": "timeseries",
   "description": "nbr of time the error occur looking up that token 15min window",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(vault_monitor_token_error_count[10m])) by (accessor, display_name)",
     "legendFormat": "{{accessor}} - {{display_name}}"
    }
   ]
  }
 ]
}